/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Login (void);
GtkWidget* create_forget_password (void);
GtkWidget* create_Authentification (void);
GtkWidget* create_Inscription (void);
GtkWidget* create_Dashbord (void);
GtkWidget* create_modificationhazem (void);
GtkWidget* create_hazemconfirmation (void);
GtkWidget* create_Eleve (void);
GtkWidget* create_tache2 (void);
GtkWidget* create_menu (void);
GtkWidget* create_verification (void);
GtkWidget* create_affiche_etud (void);
GtkWidget* create_windowajouter (void);
GtkWidget* create_windowafficher (void);
GtkWidget* create_dialog1_foyer (void);
GtkWidget* create_afiicher_st (void);
GtkWidget* create_ajouter_st (void);
GtkWidget* create_supprimer_st (void);
GtkWidget* create_modifier_st (void);
GtkWidget* create_tache2_stock (void);
GtkWidget* create_principale (void);
GtkWidget* create_menu_nutris (void);
GtkWidget* create_petit_dej (void);
GtkWidget* create_add_succe (void);
GtkWidget* create_dejeune (void);
GtkWidget* create_dinnee (void);
GtkWidget* create_dashboard (void);
GtkWidget* create_sr_Modification (void);
GtkWidget* create_confirm_supp (void);
GtkWidget* create_meilleur_menu (void);
GtkWidget* create_home (void);
GtkWidget* create_gestioncapteur (void);
GtkWidget* create_listedesalarmes (void);
GtkWidget* create_capteursdefect (void);
